/**
 * Embeddings — Cloudflare Workers AI.
 *
 * Model: @cf/baai/bge-small-en-v1.5 → 384 dimensions.
 *
 * That dimension count is the important part: it matches what the schema
 * already expects, so migration 003 (vector(384)) stays valid and nothing in
 * the database structure has to change.
 *
 * Note this IS a different model from all-MiniLM-L6-v2, so vectors generated by
 * the old local model are not comparable with these. Any existing embeddings
 * need regenerating — the seed script does that for you.
 *
 * Free tier: 10,000 Neurons/day, resets 00:00 UTC. Embeddings are cheap in
 * Neuron terms, so a portfolio demo will not come close to the ceiling.
 *
 * Env vars:
 *   CLOUDFLARE_ACCOUNT_ID
 *   CLOUDFLARE_API_TOKEN    (Workers AI read permission)
 */

const ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID
const API_TOKEN = process.env.CLOUDFLARE_API_TOKEN

const MODEL = '@cf/baai/bge-small-en-v1.5'
const MAX_ATTEMPTS = 4
const BATCH_SIZE = 32

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function callCloudflare(texts: string[]): Promise<number[][]> {
  if (!ACCOUNT_ID || !API_TOKEN) {
    throw new Error(
      'CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN must be set for embeddings.'
    )
  }

  const url = `https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/ai/run/${MODEL}`
  let lastError = ''

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${API_TOKEN}`,
        },
        body: JSON.stringify({ text: texts }),
      })

      if (res.ok) {
        const payload = await res.json()
        const vectors = payload?.result?.data
        if (!Array.isArray(vectors)) {
          throw new Error(`Unexpected response shape: ${JSON.stringify(payload).slice(0, 200)}`)
        }
        return vectors as number[][]
      }

      lastError = `${res.status} ${await res.text()}`

      // Retry on rate limit or server error; fail fast on auth/validation errors
      if (res.status !== 429 && res.status < 500) break
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err)
    }

    if (attempt < MAX_ATTEMPTS) {
      await sleep(1000 * 2 ** attempt) // 2s, 4s, 8s
    }
  }

  throw new Error(`Cloudflare embedding failed after ${MAX_ATTEMPTS} attempts: ${lastError}`)
}

/**
 * Generate a 384-dimensional embedding for a single text.
 */
export async function embedText(text: string): Promise<number[]> {
  const [embedding] = await callCloudflare([text])
  return embedding
}

/**
 * Generate embeddings for multiple texts, batched.
 */
export async function embedTexts(texts: string[]): Promise<number[][]> {
  if (texts.length === 0) return []

  const results: number[][] = []
  for (let i = 0; i < texts.length; i += BATCH_SIZE) {
    const batch = texts.slice(i, i + BATCH_SIZE)
    results.push(...(await callCloudflare(batch)))
  }
  return results
}
